# GNU Make workspace makefile autogenerated by Premake

.NOTPARALLEL:

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  gamelib_config = debug
  sandbox_config = debug
  test_config = debug
  pong_config = debug
endif
ifeq ($(config),release)
  gamelib_config = release
  sandbox_config = release
  test_config = release
  pong_config = release
endif

PROJECTS := gamelib sandbox test pong

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

gamelib:
ifneq (,$(gamelib_config))
	@echo "==== Building gamelib ($(gamelib_config)) ===="
	@${MAKE} --no-print-directory -C gamelib -f Makefile config=$(gamelib_config)
endif

sandbox: gamelib
ifneq (,$(sandbox_config))
	@echo "==== Building sandbox ($(sandbox_config)) ===="
	@${MAKE} --no-print-directory -C sandbox -f Makefile config=$(sandbox_config)
endif

test: gamelib
ifneq (,$(test_config))
	@echo "==== Building test ($(test_config)) ===="
	@${MAKE} --no-print-directory -C test -f Makefile config=$(test_config)
endif

pong: gamelib
ifneq (,$(pong_config))
	@echo "==== Building pong ($(pong_config)) ===="
	@${MAKE} --no-print-directory -C pong -f Makefile config=$(pong_config)
endif

clean:
	@${MAKE} --no-print-directory -C gamelib -f Makefile clean
	@${MAKE} --no-print-directory -C sandbox -f Makefile clean
	@${MAKE} --no-print-directory -C test -f Makefile clean
	@${MAKE} --no-print-directory -C pong -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   gamelib"
	@echo "   sandbox"
	@echo "   test"
	@echo "   pong"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"